// Pixel-art icons in the Windows 98 spirit, hand-drawn as 16×16 character grids and rendered to
// crisp SVG data URLs (no image files needed — works offline and inside the single HTML file).

const PAL = {
  k: '#000000', w: '#ffffff', s: '#c0c0c0', g: '#808080', d: '#404040', l: '#dfdfdf',
  b: '#000080', B: '#0000ff', c: '#00ffff', C: '#1084d0', t: '#008080',
  y: '#ffff00', o: '#808000', r: '#ff0000', m: '#800000', p: '#ff3d9a', P: '#800080',
  L: '#b6ff3b', G: '#008000', n: '#ff8000', e: '#43e8ff', a: '#a8d8ff',
};

const ART = {
  // МУХА herself — big red eyes, striped abdomen, glassy wings
  fly: [
    '................',
    '.....rr..rr.....',
    '....rrrkkrrr....',
    '....rrrkkrrr....',
    '.....kkkkkk.....',
    '.gg.kkkkkkkk.gg.',
    'gaag.kkkkkk.gaag',
    'gawag.kkkk.gawag',
    'gaawag.kk.gawaag',
    '.gaaaag..gaaaag.',
    '..gaaag.dd.gaag.',
    '...ggg.kddk.gg..',
    '......kkddkk....',
    '......kdkkdk....',
    '.......kkkk.....',
    '........kk......',
  ],
  // rhythia.exe — the 3×3 grid with notes and a cursor
  play: [
    'gggggggggggggggg',
    'gkkkkdkkkkdppppg',
    'gkkkkdkkkkdpkkpg',
    'gkkkkdkkkkdpkkpg',
    'gkkkkdkkkkdppppg',
    'gddddddddddddddg',
    'geeeedkkkkdkkkkg',
    'gekkedkwwkdkkkkg',
    'gekkedkwwkdkkkkg',
    'geeeedkkkkdkkkkg',
    'gddddddddddddddg',
    'gkkkkdkkkkdkkkkg',
    'gkkkkdkkkkdkkkkg',
    'gkkkkdkkkkdkkkkg',
    'gkkkkdkkkkdkkkkg',
    'gggggggggggggggg',
  ],
  // versus — two crossed swords
  versus: [
    '................',
    '.ww..........ww.',
    '.wsw........wsw.',
    '..wsw......wsw..',
    '...wsw....wsw...',
    '....wsw..wsw....',
    '.....wswwsw.....',
    '......wssw......',
    '......wssw......',
    '.....wswwsw.....',
    '..o.wsw..wsw.o..',
    '..oowsw..wswoo..',
    '...ooo....ooo...',
    '..mooo....ooom..',
    '.mm..........mm.',
    '................',
  ],
  // watch — an eye
  watch: [
    '................',
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwwbbwwwwk..',
    '.kwwwwbBBbwwwwk.',
    'kwwwwbBkkBbwwwwk',
    'kwwwwbBkkBbwwwwk',
    '.kwwwwbBBbwwwwk.',
    '..kwwwwbbwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
  ],
  // МУХА Lab — a bubbling flask
  lab: [
    '.....kkkkkk.....',
    '.....kssssk.....',
    '......kwwk......',
    '......kwwk......',
    '......kwwk...w..',
    '.....kwwwwk.w.w.',
    '....kwwwwwwk.w..',
    '...kwwwwwwwwk...',
    '..kLLLLLLLLLLk..',
    '..kLLwLLLLLLLk..',
    '.kLLLLLLLGLLLLk.',
    '.kLLLLLLLLLLwLLk',
    'kLLLGLLLLLLLLLLk',
    'kLLLLLLLLGLLLLLk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  folder: [
    '................',
    '................',
    '..ooooo.........',
    '.oyyyyyo........',
    'oyyyyyyyoooooo..',
    'owwwwwwwwwwwwwo.',
    'owyyyyyyyyyyyyok',
    'owyyyyyyyyyyyyok',
    'owyyyyyyyyyyyyok',
    'owyyyyyyyyyyyyok',
    'owyyyyyyyyyyyyok',
    'owyyyyyyyyyyyyok',
    'oooooooooooooook',
    '.kkkkkkkkkkkkkkk',
    '................',
    '................',
  ],
  floppy: [
    'kkkkkkkkkkkkkkkk',
    'kbbssssssssssbbk',
    'kbbssskksssssbbk',
    'kbbssskksssssbbk',
    'kbbssskksssssbbk',
    'kbbssssssssssbbk',
    'kbbbbbbbbbbbbbbk',
    'kbbwwwwwwwwwwbbk',
    'kbbwggggggggwbbk',
    'kbbwwwwwwwwwwbbk',
    'kbbwggggggwwwbbk',
    'kbbwwwwwwwwwwbbk',
    'kbbwwwwwwwwwwbbk',
    'kbbwwwwwwwwwwbbk',
    'kbbbbbbbbbbbbbbk',
    'kkkkkkkkkkkkkkkk',
  ],
  settings: [
    '................',
    '......kkkk......',
    '..kk..kwsk..kk..',
    '.kwsk.kwsk.kwsk.',
    '.kssskkssskksssk',
    '..kssssssssssk..',
    '...ksssggsssk...',
    'kkkkssgkkgsskkkk',
    'kwssssgkkgsssssk',
    'kkkkssgggsskkkkk',
    '...kssssssssk...',
    '..kssssssssssk..',
    '.kssskksssksssk.',
    '.kssk.kssk.kssk.',
    '..kk..kssk..kk..',
    '......kkkk......',
  ],
  notepad: [
    '.kkkkkkkkkkkk...',
    '.kBBBBBBBBBBk...',
    '.kwwwwwwwwwwk...',
    '.kwggggggggwk...',
    '.kwwwwwwwwwwk...',
    '.kwggggggwwwk...',
    '.kwwwwwwwwwwk...',
    '.kwggggggggwk...',
    '.kwwwwwwwwwwk...',
    '.kwgggggwwwwk...',
    '.kwwwwwwwwwwk...',
    '.kwggggggggwk...',
    '.kwwwwwwwwwwkg..',
    '.kkkkkkkkkkkkg..',
    '..gggggggggggg..',
    '................',
  ],
  bin: [
    '................',
    '.....kkkkkk.....',
    '...kkssssssk....',
    '..kkkkkkkkkkkk..',
    '..kwsssssssssk..',
    '...kwsgsgsgsk...',
    '...kwsgsgsgsk...',
    '...kwsgsgsgsk...',
    '...kwsgsgsgsk...',
    '...kwsgsgsgsk...',
    '...kwsgsgsgsk...',
    '...kwsgsgsgsk...',
    '...kwsgsgsgsk...',
    '...kwssssssgk...',
    '....kkkkkkkk....',
    '................',
  ],
  computer: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kwwwwwwwwwwwsk.',
    '.kwkkkkkkkkkksk.',
    '.kwkttttttttksk.',
    '.kwkttttttttksk.',
    '.kwkttttttttksk.',
    '.kwkttttttttksk.',
    '.kwkkkkkkkkkksk.',
    '.kwssssssssssGk.',
    '.kkkkkkkkkkkkkk.',
    '.....kssssk.....',
    '...kkkkkkkkkk...',
    '..kwsssssssssk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  speaker: [
    '................',
    '................',
    '......k.........',
    '.....kk....k....',
    '....ksk.....k...',
    'kkkkssk..k...k..',
    'kwwsssk...k..k..',
    'kwssssk...k..k..',
    'kwssssk...k..k..',
    'kggsssk...k..k..',
    'kkkkssk..k...k..',
    '....ksk.....k...',
    '.....kk....k....',
    '......k.........',
    '................',
    '................',
  ],
  power: [
    '................',
    '.......kk.......',
    '....kk.rr.kk....',
    '...krk.rr.krk...',
    '..krrk.rr.krrk..',
    '.krrk..rr..krrk.',
    '.krk...rr...krk.',
    '.krk...kk...krk.',
    '.krk........krk.',
    '.krrk......krrk.',
    '..krrk....krrk..',
    '...krrkkkkrrk...',
    '....kkrrrrkk....',
    '......kkkk......',
    '................',
    '................',
  ],
  info: [
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwwBBwwwwk..',
    '.kwwwwwBBwwwwwk.',
    '.kwwwwwwwwwwwwk.',
    'kwwwwwBBBwwwwwwk',
    'kwwwwwwBBwwwwwwk',
    'kwwwwwwBBwwwwwwk',
    'kwwwwwwBBwwwwwwk',
    '.kwwwwwBBwwwwwk.',
    '.kwwwwBBBBwwwwk.',
    '..kwwwwwwwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkwwkkk....',
    '.......kwk......',
    '........k.......',
  ],
  warning: [
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    '.....kykkyk.....',
    '....kyykkyyk....',
    '....kyykkyyk....',
    '...kyyykkyyyk...',
    '...kyyykkyyyk...',
    '..kyyyyyyyyyyk..',
    '..kyyyykkyyyyk..',
    '.kyyyyykkyyyyyk.',
    '.kyyyyyyyyyyyyk.',
    'kkkkkkkkkkkkkkkk',
    '.gggggggggggggg.',
    '................',
  ],
  error: [
    '.....kkkkkk.....',
    '...kkrrrrrrkk...',
    '..krrrrrrrrrrk..',
    '.krrwwrrrrwwrrk.',
    '.krrwwwrrwwwrrk.',
    'krrrrwwwwwwrrrrk',
    'krrrrrwwwwrrrrrk',
    'krrrrrwwwwrrrrrk',
    'krrrrwwwwwwrrrrk',
    '.krrwwwrrwwwrrk.',
    '.krrwwrrrrwwrrk.',
    '..krrrrrrrrrrk..',
    '...kkrrrrrrkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  mapfile: [
    '.kkkkkkkkk......',
    '.kwwwwwwwkk.....',
    '.kwwwwwwwkwk....',
    '.kwwwwwwwkkkk...',
    '.kwwwwwwwwwwk...',
    '.kwwwwpppwwwk...',
    '.kwwwwpwwpwwk...',
    '.kwwwwpwwwwwk...',
    '.kwwwwpwwwwwk...',
    '.kwwpppwwwwwk...',
    '.kwppppwwwwwk...',
    '.kwwppwwwwwwk...',
    '.kwwwwwwwwwwk...',
    '.kwwwwwwwwwwk...',
    '.kkkkkkkkkkkk...',
    '................',
  ],
  music: [
    '................',
    '.......kkkkkkkk.',
    '.......kCCCCCCk.',
    '.......kkkkkkkk.',
    '.......k......k.',
    '.......k......k.',
    '.......k......k.',
    '.......k......k.',
    '.......k......k.',
    '....kkkk...kkkk.',
    '...kCCCk..kCCCk.',
    '..kCCCCk.kCCCCk.',
    '..kCCCk..kCCCk..',
    '...kkk....kkk...',
    '................',
    '................',
  ],
  help: [
    '.....kkkkkk.....',
    '...kkCCCCCCkk...',
    '..kCCCwwwwCCCk..',
    '.kCCCwwCCwwCCCk.',
    '.kCCCCCCCwwCCCk.',
    'kCCCCCCCCwwCCCCk',
    'kCCCCCCCwwCCCCCk',
    'kCCCCCCwwCCCCCCk',
    'kCCCCCCwwCCCCCCk',
    '.kCCCCCCCCCCCCk.',
    '.kCCCCCwwCCCCCk.',
    '..kCCCCwwCCCCk..',
    '...kkCCCCCCkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  trophy: [
    '................',
    '..kkkkkkkkkkkk..',
    '.kkyyyyyyyyyykk.',
    'k.kyywyyyyyyyk.k',
    'k.kyywyyyyyyyk.k',
    '.kkyyyyyyyyyykk.',
    '...kyyyyyyyyk...',
    '....kyyyyyyk....',
    '.....kyyyyk.....',
    '......kyyk......',
    '......kook......',
    '.....kyyyyk.....',
    '....kkkkkkkk....',
    '....kooooook....',
    '....kkkkkkkk....',
    '................',
  ],
};

const cache = new Map();

/** SVG data URL for a named icon (16×16 art, drawn with crisp square pixels). */
export function iconURL(name) {
  if (cache.has(name)) return cache.get(name);
  const rows = ART[name] || ART.help;
  let rects = '';
  for (let y = 0; y < rows.length; y++) {
    const row = rows[y];
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      if (ch === '.' || !PAL[ch]) { x++; continue; }
      let run = 1;
      while (x + run < row.length && row[x + run] === ch) run++;
      rects += `<rect x="${x}" y="${y}" width="${run}" height="1" fill="${PAL[ch]}"/>`;
      x += run;
    }
  }
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">${rects}</svg>`;
  const url = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
  cache.set(name, url);
  return url;
}

/** <img> element for an icon at a given CSS size (32 = classic desktop icon, 16 = small). */
export function icon(name, size = 32, cls = '') {
  const img = document.createElement('img');
  img.src = iconURL(name);
  img.width = size;
  img.height = size;
  img.alt = '';
  img.draggable = false;
  img.className = ('px-icon ' + cls).trim();
  return img;
}

export const ICON_NAMES = Object.keys(ART);

// Validate art at import time in development: every row must be 16 characters.
for (const [name, rows] of Object.entries(ART)) {
  if (rows.length !== 16 || rows.some((r) => r.length !== 16)) {
    console.warn(`icon "${name}" is not 16×16`, rows.map((r) => r.length));
  }
}
